### PR TITLE
Create count.js

### PR DESCRIPTION
**Pull request by joelondon**
implement sql count function, with column count and where and group by options

### CODE REVIEW

**Comment by mapsgeek** [comment]
@tobinbradley i didn't know that i can pass a function as a parameter, is count() a postgis function?

**Comment by joelondon** [comment]
me neither, though i just tried it and it works, so this PR can be dropped and i'll propose a README amendment instead, thanks 🙂
________________________________

**Comment by joelondon** [comment]
not needed as count is provided by using count(column_name) in the query route

**Comment by tobinbradley** [comment]
@mapsgeek count() is a PostgreSQL function. It's part of the ANSI SQL standard, so you'll find it in just about every SQL database.

Parameters on queries where you'd normally use functions in a SQL statement (like `columns` or `filter` but not things like `limit`) can include any function the user has access to, including custom functions you create in the database. I'll add a note about it to the README.

**Pull request closed without merging**
