### PR TITLE
Dirt on Docker

### PR DESCRIPTION
**Pull request by rbrtmrtn**
Hello @tobinbradley!

I've used Dirt for a few things lately and it has saved me _a ton_ of time, so first off — a huge thank you for your vision and work on this project 🙏 

I wanted to be able to spin up Dirt quickly without copying the code base or writing a config file, so I thought containerizing might help. I wrote a `Dockerfile`, made a few small tweaks, and was able to run Dirt with just the `POSTGRES_CONNECTION` environment variable. I thought I'd create a PR for this in case it's useful for anyone else. I added some notes to `README.md` on how it the containerized way.

One thing I wasn't totally sure about: getting this to work required changing the the host Fastify is listening on from `localhost` to `0.0.0.0`. I'm not sure if this has any security implications, but just wanted to call that out.

Cheers!

### CODE REVIEW

**Comment by mtravis** [comment]
This sounds great. Thanks for sharing.

**Comment by tobinbradley** [comment]
This is awesome!

One wrinkle - I'm hopefully doing a new release early this coming week that moves to Fastify 4 and gets rid of the config.json file entirely. You'll be able to set everything via environmental variables or putting them in a .env file. The defaults in the config.json file will be applied in index.js for everything that isn't the db connection if an environmental var for those isn't present. That should make for simpler deploys and easier configurations with no fiddling about with config files necessary. 

I think what I can do is make that release, tweak the pull request slightly (like remove the `RUN mv...` line from the Docker file that won't be need anymore) and it should be good to go. Stay tuned, and thanks again for this pull request - I think it's going to be very helpful for a lot of people.

**Comment by tobinbradley** [comment]
Can you make another pull request based on the current master? I'm having a hard time getting these edits to sync with the new stuff. Really all I need is:

* no longer need changes to index.js
* remove config.json bit from Dockerfile
* README.md insertion based on current README.md
* .dockerignore is good

**Comment by tobinbradley** [comment]
Accidentally deleted my first comment :).

The master branch now uses env vars for everything, and the config.json file is no more. They can be set on the system or at run time or in a .env file, with the database connection being the only required one (see updated README). Unfortunately that was all mostly done already when I got your pull request. 

With everything able to be set at run time and no moving files around to get started it should make life easier for everybody.

**Comment by rbrtmrtn** [comment]
Awesome to see these changes @tobinbradley ! Let me rebase, tweak the `Dockerfile` to not use the config file, and reopen this PR, if that sounds good.

**Comment by tobinbradley** [comment]
That would be fantastic!

**Pull request closed without merging**
